services:
  engine:
    build:
      context: ./engine
    container_name: zooscape-engine
    healthcheck:
      test: curl http://localhost:5000/bothub
      interval: 50ms
      start_interval: 50ms
      start_period: 50ms
      retries: 20
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/var/log/zooscape
    environment:
      GameSettings__TickDuration: 150
      GameSettings__StartGameTimeout: 9999

  refbot-0:
    build:
      context: ./Bots/ReferenceBot
      dockerfile: Dockerfile
    container_name: zooscape-refbot-0
    depends_on:
      engine:
        condition: service_healthy
    environment:
      RUNNER_IPV4: http://engine
      BOT_NICKNAME: RefBot-0

  g2mcts:
    build:
      context: ./Bots/MCTSBot
      dockerfile: Dockerfile
    container_name: g2-mcts
    depends_on:
      engine:
        condition: service_healthy
    environment:
      RUNNER_IPV4: http://engine
      BOT_NICKNAME: g2-mcts

  o4mcts:
    build:
      context: ./Bots/mctso4
      dockerfile: Dockerfile
    container_name: o4mcts
    depends_on:
      engine:
        condition: service_healthy
    environment:
      RUNNER_IPV4: http://engine
      BOT_NICKNAME: o4mcts

  basic-bot:
    build:
      context: ./Bots/BasicBot
    container_name: basicbot
    depends_on:
      engine:
        condition: service_healthy
    environment:
      RUNNER_IPV4: http://engine
      BOT_NICKNAME: BasicBot

  amcts:
    build:
      context: ./Bots/AdvancedMCTSBot
      dockerfile: Dockerfile
    container_name: advanced-mcts
    environment:
      RUNNER_IPV4: http://engine
      BOT_NICKNAME: AdvancedMCTS

  visualizer:
    build:
      context: .
      dockerfile: visualizer-2d/Dockerfile
    container_name: visualizer
    ports:
      - "8080:80"
